### ISSUE TITLE
Unable to use PTI in Zend Studio 10

### ISSUE THREAD

**Issue by danielmitd** [PHPsrc/PHP-Tool-Integration#2]
Currently I'm unable to use any of the PTI Version in Zend Studio 10:

```
An internal error occurred during: "PHP CodeSniffer".
org.eclipse.php.internal.debug.core.launching.PHPLaunchUtilities.getCommandLine(Lorg/eclipse/debug/core/ILaunchConfiguration;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
```

Any idea how to fix this?

**Comment by zulus** [comment]
You need this: https://github.com/PHPsrc/org.phpsrc.eclipse.pti.core/pull/1

**Comment by itayf** [comment]
Hey Daniel.
I'm a developer at Zend, and I fixed it.
It'll be available in the next Studio update.
Best Regards,
Itay

**Comment by danielmitd** [comment]
Hi @itayf, do you know when the next update will be released?

**Comment by danielmitd** [comment]
so @itayf the update has not resolved my issue. And @zulus I can see the "workaround" works, but i've no idea how to apply it. I'm only a eclipse user,... with no idea of all this java plugin stuff.

**Comment by marcospassos** [comment]
I've the same issue and I'm using the lasted version available.

@danielmitd Do you managed get it work?

**Comment by greew** [comment]
Same problem here. Can anyone give an explanation of how to compile the java and use the new setup?

**Comment by asgrim** [comment]
+1 same problem but in PDT 3.1.2 on Eclipse Juno

**Comment by danielmitd** [comment]
@marcospassos not really...

**Comment by zulus** [comment]
@greew You can download this file: http://test.w3des.net/github/org.phpsrc.eclipse.pti.core_1.6.0.R20111119000000.jar
and replace it in eclipse/plugins folder

**Comment by itayf** [comment]
@danielmitd @marcospassos @greew @asgrim 
Sorry for the late response- had some holidays....
The latest build is available on the beta.zend.com update site.
To use it you should also change the <Zend_Studio_Home>/configuration/config.ini to
com.zend.php.customization.site.url=http://beta.zend.com/studio-eclipse/updates-extra/10_0
or set url redirection from downloads.zend.com -> beta.zend.com in hosts file.

If you have any problems I'll be available to answer now

**Comment by marcospassos** [comment]
Hello @itayf,

Thanks for your support.

Still not work for me. I set the setting in config.ini, then `Check for Updates` > _I updated all that was available_. After restart:

```
An internal error occurred during: "Validating (...)".
org.eclipse.php.internal.debug.core.launching.PHPLaunchUtilities.getCommandLine(Lorg/eclipse/debug/core/ILaunchConfiguration;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
```

Without success, I download the file mentioned by@zulus, replacing in plugin's folder, but also without any success.

**Comment by zulus** [comment]
Sorry by fail. I uploaded invalid (original file), can you try again?

**Comment by marcospassos** [comment]
Works like a charm! Thanks so much!

**Comment by danielmitd** [comment]
same over here. thanks @zulus. and thanks @itayf for the feeback about the beta channel.

**Comment by greew** [comment]
@zulus Great! Thanks for the updated file. It works like a charm now! :+1:

**Comment by asgrim** [comment]
@zulus This update didn't appear to work for me. I am still getting:

```
An internal error occurred during: "PHPUnit".
org.eclipse.php.internal.debug.core.launching.PHPLaunchUtilities.getCommandLine(Lorg/eclipse/debug/core/ILaunchConfiguration;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
```

I am running Eclipse Juno 4.2.2, PDT 3.1.2 and PTI 1.5.9.

The update sites I have configured:
- http://download.eclipse.org/releases/juno
- http://www.phpsrc.org/eclipse/pti-dev/
- http://download.eclipse.org/eclipse/updates/4.2

![pdt](https://f.cloud.github.com/assets/496145/338278/23720642-9d0a-11e2-98b5-80e892662a5b.png)

I notice my version is 1.5.9 but the .jar above seems to be for 1.6.0 ? Is this perhaps what is wrong? How do I get 1.6.0 ?

**Comment by greew** [comment]
@asgrim You can get PTI 1.6.0 by using http://www.phpsrc.org/eclipse/pti/ instead of pti-dev

**Comment by asgrim** [comment]
@greew Thanks - that's updated now. Seems odd that the pti-dev channel has an older version than the stable version :)

I now have a different issue but will investigate that separately. Thanks everyone.
