### ISSUE TITLE
can not use PHPUnit with eclipse juno 4.2.2 and PTI 1.6.0.R20111119000000 under Ubuntu 13.04

### ISSUE THREAD

**Issue by steros** [PHPsrc/PHP-Tool-Integration#3]
When I try to create a test case from a file a popup opens where to create that test, all is filled out as expected. But when I click finish it only creates the folder ("test" in my case) and no file, also the popup does not close.

When I manually create a test file and run the test I get this error:
An internal error occurred during: "PHPUnit".
org.eclipse.php.internal.debug.core.launching.PHPLaunchUtilities.getCommandLine(Lorg/eclipse/debug/core/ILaunchConfiguration;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;

PHPUnit is 3.7.19

**Comment by zulus** [comment]
you can try my solution from #2

**Comment by steros** [comment]
Yes I saw that. Sorry what is the solution?
You link a file in that ticket which is the version I have and the problem there seems to refer to an older version.
Seems I misunderstand something.

**Comment by zulus** [comment]
You have to build this plugin https://github.com/PHPsrc/org.phpsrc.eclipse.pti.core with my path, for example from my fork https://github.com/zulus/org.phpsrc.eclipse.pti.core/tree/pdt-3.1.2 (branch pdt-3.1.2)

**Comment by steros** [comment]
Thanks!

To complete for others:
- download the code from the link https://github.com/zulus/org.phpsrc.eclipse.pti.core/tree/pdt-3.1.2
- HAVE PTI already installed! (otherwise dependencies are missing)
- import the code in eclipse as a new project
- open the project and go to the java perspective
- open the plugin.xml and go to the "overview" tab
- at the bottom you will find a link to an "export wizard", click it
- in the wizard select as output directory the root directory of your eclipse installation and finish the export
  this will create a .jar file in the plugins directory
- restart eclipse

**Comment by steros** [comment]
That fix does not work for eclipse juno 64bit version.

**Comment by steros** [comment]
https://github.com/PHPsrc/org.phpsrc.eclipse.pti.core/pull/1#issuecomment-15315031
This comment fixes the bug.
I edited the code, may someone review this?

FYI: You have to edit the file
https://github.com/PHPsrc/org.phpsrc.eclipse.pti.core/edit/master/src/org/phpsrc/eclipse/pti/core/launching/PHPToolExecutableLauncher.java
with the code from the comment and export the plugin via eclipse as described above.

**Comment by bglase** [comment]
@steros, I'm not much of an expert on building plugins, and I cannot seem to get this plugin to compile in a way that others can install it.  Following your steps above, I can install it into my local eclipse, but when I export it to an archive or a directory, other people can't 'Install New Software' and point to the resulting .jar file to install the PTI core.  Do you have any way to get the update into an installable form?

**Comment by steros** [comment]
I'm not an expert too.
But I guess you have to bundle the parts you need with the core. I guess you can do that with a feature project as described here:
http://www.vogella.com/articles/EclipseFeatureProject/article.html

**Comment by pulse00** [comment]
fyi: we have a solid launching infrastructure over there at [PEX-Core](https://github.com/pdt-eg/Core-Plugin/tree/master/org.pdtextensions.core/src/org/pdtextensions/core/launch). 

The above mentioned solutions seems rather tedious for most users. Maybe we can try to consolidate the launching situation?

@skiera I guess you don't have much time, maybe i can help with this issue here? What's your plans for the PHPSrc plugins?

**Comment by skiera** [comment]
Hi Robert,

yes, unfortunately I have not much time for PTI and I will look for some one how is interested I taking over the further development. I hope to find some time next week to fix most of the actual problems and if you like, you can help me :-) I you like, we could skype and talk about it :-)

Best regards,
Sven

-----Original message-----
